import { AnalyzerResult, Contracts } from '../types.js';

/**
 * Contracts analyzer - Phase 2 (LLM required).
 * For Phase 1, generates a placeholder contracts file.
 */
export async function analyzeContracts(
  _cwd: string,
  _files: string[],
): Promise<AnalyzerResult<Contracts>> {
  return {
    name: 'contracts',
    data: {
      contracts: [],
      generated: false,
      requiresLLM: true,
    },
    deterministic: false,
  };
}

/**
 * Generate placeholder intent.yml content.
 */
export function generatePlaceholderContracts(): string {
  return `# Behavioral Contracts
# Auto-generated by dontreadme
# Run \`dontreadme generate --only contracts\` with an LLM provider for full analysis.

contracts: []
# Example:
# - function: authenticateUser
#   file: src/auth/login.ts
#   preconditions:
#     - email must be a valid email format
#     - password must be non-empty
#   postconditions:
#     - returns a valid JWT token on success
#     - throws AuthError on invalid credentials
#   invariants:
#     - password is never logged or stored in plain text
#   sideEffects:
#     - creates a session record in the database
#     - emits a login event
`;
}
