import { AnalyzerResult, UnderstandingMeta } from '../types.js';

/**
 * Understanding analyzer - Phase 2 (LLM required).
 * For Phase 1, generates a placeholder understanding.md.
 */
export async function analyzeUnderstanding(
  _cwd: string,
  _files: string[],
): Promise<AnalyzerResult<UnderstandingMeta>> {
  return {
    name: 'understanding',
    data: {
      generated: false,
      requiresLLM: true,
      placeholder: true,
    },
    deterministic: false,
  };
}

/**
 * Generate placeholder understanding.md content.
 */
export function generatePlaceholderUnderstanding(
  projectName: string,
  framework: string | null,
  language: string,
  fileCount: number,
): string {
  return `# ${projectName}

> This understanding document was generated by dontreadme.
> Run \`dontreadme generate --only understanding\` with an LLM provider to generate a full analysis.

## Overview

This is a ${language} ${framework ? `${framework} ` : ''}project with ${fileCount} source files.

## Architecture

*Requires LLM analysis. See \`architecture.json\` for the deterministic component graph.*

## Key Technologies

- Language: ${language}
${framework ? `- Framework: ${framework}\n` : ''}\

## Main User Flows

*Requires LLM analysis to identify user flows.*
`;
}
